### ISSUE TITLE
Hey , You Build kernel from source stock ??? . Kernel Source encrypted

### ISSUE THREAD

**Issue by nguyenhung9x2020** [AshuSharma7/android_device_asus_x01ad#1]
https://github.com/AshuSharma7/android_device_asus_x01ad/blob/4dbf0cadb603cd2eecb545dcb424fb00f3d8e98d/BoardConfig.mk#L48

**Comment by AshuSharma7** [comment]
> https://github.com/AshuSharma7/android_device_asus_x01ad/blob/4dbf0cadb603cd2eecb545dcb424fb00f3d8e98d/BoardConfig.mk#L48

Yeah I'm using Stock kernel source provided by asus
Kernel Source is not encrypted
